// GENERATED by tools/gen_assets.py - do not edit.
#ifndef _UI_ASSETS_H_
#define _UI_ASSETS_H_

#include "ui_types.h"

extern const ui_font_t font_title;   // Barlow-SemiBold 22px
extern const ui_font_t font_label;   // Barlow-SemiBold 15px
extern const ui_font_t font_body;   // Barlow-Medium 15px
extern const ui_font_t font_small;   // Barlow-Medium 13px
extern const ui_font_t font_unit;   // Barlow-SemiBold 13px
extern const ui_font_t font_val;   // BarlowCondensed-Bold 32px
extern const ui_font_t font_mid;   // BarlowCondensed-Bold 96px
extern const ui_font_t font_big;   // BarlowCondensed-Bold 136px

extern const ui_bitmap_t icon_sun;
extern const ui_bitmap_t icon_house;
extern const ui_bitmap_t icon_cloud_rain;
extern const ui_bitmap_t icon_drop;
extern const ui_bitmap_t icon_drop_empty;
extern const ui_bitmap_t icon_wifi;

#endif // _UI_ASSETS_H_
